sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mannu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mannu/docker-react npm run test -- --coverage
